### ISSUE TITLE
Multiple SECTIONs make program crash

### ISSUE THREAD

**Issue by diemoschwarz** [philsquared/Catch#571]
Maybe this is in my code, but I wrote a test case that runs fine with just one section, but as soon as I split it into two sections, the program crashes.
Debugging catch showed that at some point in the section switch, some values within my objects get overwritten, causing the crash a little later.

If you care to look, in pipo-sequence-test.cpp, see SPLIT_SECTIONS at the end:
[catch-crash-with-sections.zip](https://github.com/philsquared/Catch/files/94777/catch-crash-with-sections.zip)

This is on MacOS 10.10, run it with:

clang++ pipo-sequence-test.cpp
./a.out

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
pipo-sequence-test.cpp:92: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases: 1 | 1 failed
assertions: 9 | 8 passed | 1 failed
```
Thanks!

**Comment by nabijaczleweli** [comment]
```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

d:\Pobieranie\asdf>g++ -std=c++14 pipo-sequence-test.cpp
In file included from PiPoSequence.h:13:0,
                 from pipo-sequence-test.cpp:5:
PiPo.h:944:110: warning: converting to non-pointer type 'unsigned int' from NULL [-Wconversion-null]
   PiPoScalarAttr(PiPo *pipo, const char *name, const char *descr, bool changesStream, unsigned int initVal = NULL) :
                                                                                                              ^
PiPo.h:1184:134: warning: converting to non-pointer type 'unsigned int' from NULL [-Wconversion-null]
   PiPoVarSizeAttr(PiPo *pipo, const char *name, const char *descr, bool changesStream, unsigned int size = 0, unsigned int initVal = NULL) :
                                                                                                                                      ^
In file included from pipo-sequence-test.cpp:6:0:
PiPoConst.h: In member function 'virtual int PiPoConst::streamAttributes(bool, double, double, unsigned int, unsigned int, const char**, bool, double, unsigned int)':
PiPoConst.h:86:22: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
         outlabels[i] = "unnamed";
                      ^

d:\Pobieranie\asdf>a
<<<OS popup — program crashed>>>

d:\Pobieranie\asdf>gdb a
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-msys".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
Reading symbols from a...done.
(gdb) run
Starting program: /d/Pobieranie/asdf/a
[New Thread 7072.0x604]
[New Thread 7072.0x2c38]
[New Thread 7072.0x2fcc]

Program received signal SIGSEGV, Segmentation fault.
0x000000000042f6e6 in PiPoScale::frames(double, double, float*, unsigned int, unsigned int) ()
(gdb) q
A debugging session is active.

        Inferior 1 [process 7072] will be killed.

Quit anyway? (y or n) y

d:\Pobieranie\asdf>
```

Looks to me like *your* code `SIGSEGV`s

**Comment by diemoschwarz** [comment]
it surely does!  What makes me post this here is that it only segfaults when more than one catch SECTION is defined.  If you comment "#define SPLIT_SECTIONS 1" on line 88, everything runs.
Is there anything non-trivial happening between sections, that brings to light a bug lurking in my code?

**Comment by nabijaczleweli** [comment]
>  Is there anything non-trivial happening between sections, that brings to light a bug lurking in my code?

Highly probable, that's how UB may present yourself.

**Comment by nabijaczleweli** [comment]
Actually...
```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved

d:\Pobieranie\asdf>g++ -std=c++14 pipo-sequence-test_mod.cpp
In file included from PiPoSequence.h:13:0,
                 from pipo-sequence-test_mod.cpp:5:
PiPo.h:944:110: warning: converting to non-pointer type 'unsigned int' from NULL [-Wconversion-null]
   PiPoScalarAttr(PiPo *pipo, const char *name, const char *descr, bool changesStream, unsigned int initVal = NULL) :
                                                                                                              ^
PiPo.h:1184:134: warning: converting to non-pointer type 'unsigned int' from NULL [-Wconversion-null]
   PiPoVarSizeAttr(PiPo *pipo, const char *name, const char *descr, bool changesStream, unsigned int size = 0, unsigned int initVal = NULL) :
                                                                                                                                      ^
In file included from pipo-sequence-test_mod.cpp:6:0:
PiPoConst.h: In member function 'virtual int PiPoConst::streamAttributes(bool, double, double, unsigned int, unsigned int, const char**, bool, double, unsigned int)':
PiPoConst.h:86:22: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
         outlabels[i] = "unnamed";
                      ^
d:/Programy/Programowanie/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file a.exe: Permission denied
collect2.exe: error: ld returned 1 exit status

d:\Pobieranie\asdf>a

d:\Pobieranie\asdf>gdb a
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-msys".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
Reading symbols from a...done.
(gdb) run
Starting program: /d/Pobieranie/asdf/a
[New Thread 14496.0x3238]
[New Thread 14496.0x1d90]
[New Thread 14496.0x7a8]

Program received signal SIGSEGV, Segmentation fault.
0x000000000042f6e6 in PiPoScale::frames(double, double, float*, unsigned int, unsigned int) ()
(gdb) q
A debugging session is active.

        Inferior 1 [process 14496] will be killed.

Quit anyway? (y or n) y

d:\Pobieranie\asdf>
```
Despite removing line 88.

**Comment by diemoschwarz** [comment]
great, thanks for confirming that its a bug in my code that doesn't show in MacOS! 
Time for valgrind, I guess. 
Closing this issue.
