### ISSUE TITLE
SelfTest binary leaks memory (or at least ASAN thinks so).

### ISSUE THREAD

**Issue by horenmar** [philsquared/Catch#783]
I found an old issue that talked about ASAN errors. Since it was during multithreaded run, old and without specifics, it was pointless, but I decided to look at the current state.

ASAN reports several leaks in the SelfTest binary, mostly in generators, but some of them I really don't know how to read (the ones at the top).
```

=================================================================
==17940==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 85 byte(s) in 1 object(s) allocated from:
    #0 0x5a1090 in operator new(unsigned long) (/catch-path/Build/SelfTest+0x5a1090)
    #1 0x7fb46c1f296c in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x12196c)
    #2 0x7ffe1bb02aff  (<unknown module>)
    #3 0x7ffe1bb02abf  (<unknown module>)

Indirect leak of 85 byte(s) in 1 object(s) allocated from:
    #0 0x5a1090 in operator new(unsigned long) (/catch-path/Build/SelfTest+0x5a1090)
    #1 0x7fb46c1f296c in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x12196c)
    #2 0x7ffe1bb0309f  (<unknown module>)
    #3 0x7ffe1bb0307f  (<unknown module>)

Indirect leak of 85 byte(s) in 1 object(s) allocated from:
    #0 0x5a1090 in operator new(unsigned long) (/catch-path/Build/SelfTest+0x5a1090)
    #1 0x7fb46c1f296c in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x12196c)
    #2 0x7ffe1bb02b5f  (<unknown module>)
    #3 0x7ffe1bb02b3f  (<unknown module>)

Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x5a1090 in operator new(unsigned long) (/catch-path/Build/SelfTest+0x5a1090)
    #1 0x69fcc3 in Catch::createGeneratorsForTest() /catch-path/include/internal/catch_generators_impl.hpp:81:16
    #2 0x70c2c5 in Catch::Context::getGeneratorsForCurrentTest() /catch-path/include/internal/catch_context_impl.hpp:73:30
    #3 0x70b67c in Catch::Context::getGeneratorIndex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) /catch-path/include/internal/catch_context_impl.hpp:32:20
    #4 0x63c669 in Catch::CompositeGenerator<IntPair*>::operator IntPair*() const /catch-path/include/internal/catch_generators.hpp:90:31
    #5 0x635565 in ____C_A_T_C_H____T_E_S_T____2() /catch-path/projects/SelfTest/GeneratorTests.cpp:38:18
    #6 0x6e332a in Catch::FreeFunctionTestCase::invoke() const /catch-path/include/internal/catch_test_case_registry_impl.hpp:151:13
    #7 0x6a12d9 in Catch::TestCase::invoke() const /catch-path/include/internal/catch_test_case_info.hpp:176:9
    #8 0x701513 in Catch::RunContext::invokeActiveTestCase() /catch-path/include/internal/catch_run_context.hpp:314:13
    #9 0x700de5 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /catch-path/include/internal/catch_run_context.hpp:285:21
    #10 0x6d8437 in Catch::RunContext::runTest(Catch::TestCase const&) /catch-path/include/internal/catch_run_context.hpp:104:21
    #11 0x69bb4c in Catch::runTests(Catch::Ptr<Catch::Config> const&) /catch-path/include/internal/../catch_session.hpp:78:27
    #12 0x72c257 in Catch::Session::run() /catch-path/include/internal/../catch_session.hpp:186:42
    #13 0x6e033f in Catch::Session::run(int, char const* const*) /catch-path/include/internal/../catch_session.hpp:165:30
    #14 0x6ae1fb in main /catch-path/include/internal/catch_default_main.hpp:15:12
    #15 0x7fb46b1e082f in __libc_start_main /build/glibc-t3gR2i/glibc-2.23/csu/../csu/libc-start.c:291

...
```
The full output is at pastebin, because it has ~50k.
http://pastebin.com/WCBAbWbK

**Comment by philsquared** [comment]
Looks like they all refer to the same Generators leak (well, in your truncated sample, anyway).
I had a quick look at the code and the leak is fairly obvious (fortunately generators aren't used much - or officially supported yet).
I've fixed that leak and pushed the changes. They should end up in the single include in the next release, but feel free to run your ASAN tests again before that.

**Comment by horenmar** [comment]
It's clean now.
