### ISSUE TITLE
MemorySanitizer use-of-uninitialized-value

### ISSUE THREAD

**Issue by johnthagen** [philsquared/Catch#899]
## Description
Clang [MemorySanitizer](https://clang.llvm.org/docs/MemorySanitizer.html) finds a `use-of-uninitialized-value` when running a basic `TEST_CASE`. This may be happening during Catch's registration process.

It would be great to fix this, because I'd like to run MemorySanitizer on my unit tests to ensure that the code it is testing does not have memory safety/access issues, but since it fails immediately due to Catch, it currently is not possible.

### Steps to reproduce
- OS: Ubuntu 16.04 x64
- Clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final) (`sudo apt install clang`)
- Fix Ubuntu 16.04 `llvm-symbolizer` path (see http://stackoverflow.com/a/43228843/1398841) to get nice stack traces.

```bash
$ sudo ln -s /usr/bin/llvm-symbolizer-3.8 /usr/bin/llvm-symbolizer
```

Create sample program (`catch_main.cpp`):

```cpp
#define CATCH_CONFIG_MAIN

#include "catch.hpp"

TEST_CASE("Test name", "[tag]") {
    REQUIRE(1 == 1);
}
```

Place `catch.hpp` 1.9.3 in the same directory as the above file, compile, and run.

#### Normal MemorySanitizer Build
```bash
$ clang++ -fsanitize=memory -fno-omit-frame-pointer -g catch_main.cpp; ./a.out 
==48417==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x53db8c in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_get_insert_unique_pos(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:1807:7
    #1 0x53d65e in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_insert_unique(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:1863:4
    #2 0x53cf5a in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Catch::Ptr<Catch::IReporterFactory>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::insert(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_map.h:613:16
    #3 0x53cbfc in Catch::ReporterRegistry::registerReporter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::Ptr<Catch::IReporterFactory> const&) /home/user/workspace/catch_test/./catch.hpp:7321:13
    #4 0x4bab4b in Catch::(anonymous namespace)::RegistryHub::registerReporter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::Ptr<Catch::IReporterFactory> const&) /home/user/workspace/catch_test/./catch.hpp:7449:17
    #5 0x4d1130 in Catch::ReporterRegistrar<Catch::JunitReporter>::ReporterRegistrar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/user/workspace/catch_test/./catch.hpp:9734:13
    #6 0x41eab6 in __cxx_global_var_init.61 /home/user/workspace/catch_test/./catch.hpp:10470:5
    #7 0x41f137 in _GLOBAL__sub_I_catch_main.cpp /home/user/workspace/catch_test/catch_main.cpp
    #8 0x63bc7c in __libc_csu_init (/home/user/workspace/catch_test/a.out+0x63bc7c)
    #9 0x7fa7a38347be in __libc_start_main /build/glibc-9tT8Do/glibc-2.23/csu/../csu/libc-start.c:247
    #10 0x41f178 in _start (/home/user/workspace/catch_test/a.out+0x41f178)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:1807:7 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_get_insert_unique_pos(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Exiting
```

#### MemorySanitizer with Origin Tracking

```bash
$ clang++ -fsanitize=memory -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize-memory-track-origins=2 -g catch_main.cpp; ./a.out 
==48431==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x640a09 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_get_insert_unique_pos(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:1807:7
    #1 0x63fa6b in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_insert_unique(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:1863:4
    #2 0x63e370 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Catch::Ptr<Catch::IReporterFactory>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::insert(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_map.h:613:16
    #3 0x63dcbb in Catch::ReporterRegistry::registerReporter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::Ptr<Catch::IReporterFactory> const&) /home/user/workspace/catch_test/./catch.hpp:7321:13
    #4 0x4ef6fe in Catch::(anonymous namespace)::RegistryHub::registerReporter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::Ptr<Catch::IReporterFactory> const&) /home/user/workspace/catch_test/./catch.hpp:7449:17
    #5 0x4f0a5e in non-virtual thunk to Catch::(anonymous namespace)::RegistryHub::registerReporter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::Ptr<Catch::IReporterFactory> const&) /home/user/workspace/catch_test/./catch.hpp:7448:26
    #6 0x5259a3 in Catch::ReporterRegistrar<Catch::JunitReporter>::ReporterRegistrar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/user/workspace/catch_test/./catch.hpp:9734:13
    #7 0x41ec9d in __cxx_global_var_init.61 /home/user/workspace/catch_test/./catch.hpp:10470:5
    #8 0x41f4b7 in _GLOBAL__sub_I_catch_main.cpp /home/user/workspace/catch_test/catch_main.cpp
    #9 0x8b9c5c in __libc_csu_init (/home/user/workspace/catch_test/a.out+0x8b9c5c)
    #10 0x7f1ee2c7c7be in __libc_start_main /build/glibc-9tT8Do/glibc-2.23/csu/../csu/libc-start.c:247
    #11 0x41f4f8 in _start (/home/user/workspace/catch_test/a.out+0x41f4f8)

  Uninitialized value was stored to memory at
    #0 0x640e4e in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_get_insert_unique_pos(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:1811:8
    #1 0x63fa6b in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_insert_unique(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:1863:4
    #2 0x63e370 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Catch::Ptr<Catch::IReporterFactory>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::insert(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_map.h:613:16
    #3 0x63dcbb in Catch::ReporterRegistry::registerReporter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::Ptr<Catch::IReporterFactory> const&) /home/user/workspace/catch_test/./catch.hpp:7321:13
    #4 0x4ef6fe in Catch::(anonymous namespace)::RegistryHub::registerReporter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::Ptr<Catch::IReporterFactory> const&) /home/user/workspace/catch_test/./catch.hpp:7449:17
    #5 0x4f0a5e in non-virtual thunk to Catch::(anonymous namespace)::RegistryHub::registerReporter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::Ptr<Catch::IReporterFactory> const&) /home/user/workspace/catch_test/./catch.hpp:7448:26
    #6 0x5259a3 in Catch::ReporterRegistrar<Catch::JunitReporter>::ReporterRegistrar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/user/workspace/catch_test/./catch.hpp:9734:13
    #7 0x41ec9d in __cxx_global_var_init.61 /home/user/workspace/catch_test/./catch.hpp:10470:5
    #8 0x41f4b7 in _GLOBAL__sub_I_catch_main.cpp /home/user/workspace/catch_test/catch_main.cpp
    #9 0x8b9c5c in __libc_csu_init (/home/user/workspace/catch_test/a.out+0x8b9c5c)

  Uninitialized value was created by a heap allocation
    #0 0x48c9d0 in operator new[](unsigned long) (/home/user/workspace/catch_test/a.out+0x48c9d0)
    #1 0x645b83 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:104:27
    #2 0x645692 in __gnu_cxx::__alloc_traits<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > > >::allocate(std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/alloc_traits.h:182:14
    #3 0x644ba1 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_get_node() /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:491:16
    #4 0x644892 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_create_node(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:513:21
    #5 0x64454e in std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >* std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_Alloc_node::operator()<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > const&) const /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:459:13
    #6 0x64264c in std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_insert_<std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_Alloc_node>(std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > const&, std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_Alloc_node&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:1509:19
    #7 0x63fd7a in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_insert_unique(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:1868:16
    #8 0x63e370 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Catch::Ptr<Catch::IReporterFactory>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::insert(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_map.h:613:16
    #9 0x63dcbb in Catch::ReporterRegistry::registerReporter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::Ptr<Catch::IReporterFactory> const&) /home/user/workspace/catch_test/./catch.hpp:7321:13
    #10 0x4ef6fe in Catch::(anonymous namespace)::RegistryHub::registerReporter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::Ptr<Catch::IReporterFactory> const&) /home/user/workspace/catch_test/./catch.hpp:7449:17
    #11 0x4f0a5e in non-virtual thunk to Catch::(anonymous namespace)::RegistryHub::registerReporter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::Ptr<Catch::IReporterFactory> const&) /home/user/workspace/catch_test/./catch.hpp:7448:26
    #12 0x525243 in Catch::ReporterRegistrar<Catch::XmlReporter>::ReporterRegistrar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/user/workspace/catch_test/./catch.hpp:9734:13
    #13 0x41ea0d in __cxx_global_var_init.59 /home/user/workspace/catch_test/./catch.hpp:10227:6
    #14 0x41f4b2 in _GLOBAL__sub_I_catch_main.cpp /home/user/workspace/catch_test/catch_main.cpp
    #15 0x8b9c5c in __libc_csu_init (/home/user/workspace/catch_test/a.out+0x8b9c5c)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_tree.h:1807:7 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Catch::Ptr<Catch::IReporterFactory> > > >::_M_get_insert_unique_pos(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Exiting
```

### Extra information

* Catch version: **v1.9.3**
* Operating System: **Ubuntu 16.04 x64**
* Compiler+version: **Clang v3.8.0**
```

**Comment by horenmar** [comment]
Do you have properly instrumented libstdc++?

Because this is very, very, very likely to be a duplicate of #731 and #831, which were both FP caused by MSan not playing nice with standard libstdc++.

**Comment by johnthagen** [comment]
I knew that all user code had to be compiled with MSan, but didn't notice from reading the documentation that [even libstdc++ needed to as well](http://stackoverflow.com/a/20784130/1398841). I'll close this issue, thanks for the feedback.
